version: '3'
services:
  app_server:
    container_name: app-server
    build: ./app-server
    environment:
      - FLASK_APP=/srv/app/wsgi.py
      - FLASK_DEBUG=1
      - FLASK_SECRET_KEY=sandbox
    volumes:
      - ./app-server/app:/srv/app
    # command: flask run --host=0.0.0.0 --port=5000
    command: gunicorn wsgi:app --chdir /srv/app -b 0.0.0.0:5000

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  http_server:
    container_name: http-server
    image: nginx:1.15-alpine
    build: ./http-server
    volumes:
      - ./http-server/nginx.config:/etc/nginx/sites-enabled/default
      # - ./data/nginx:/etc/nginx/conf.d
      - ./web-client/app/static:/srv/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
